// Generated by https://quicktype.io
export interface Country {
    flag: string;
    name: string;
    code: string;
}

export const CountryDefaultState: Country = {
    flag: 'https://flagcdn.com/w320/do.png',
    name: 'Dominican Republic',
    code: 'DO',
};


export interface CountryEndpoint {
    flags: Flags;
    name:  Name;
    cca2:  string;
}

export interface Flags {
    png: string;
    svg: string;
    alt: string;
}

export interface Name {
    common:     string;
    official:   string;
    nativeName: { [key: string]: NativeName };
}

export interface NativeName {
    official: string;
    common:   string;
}
